### ISSUE TITLE
Plugin uses wrong name

### ISSUE THREAD

**Issue by meolic** [clear-code/redmine_common_mark#9]
/home/redmine/redmine-4.1.0/lib/redmine/plugin.rb:102:in `register': Plugin not found. The directory for plugin common_mark should be /home/redmine/redmine-4.1.0/plugins/common_mark. (Redmine::PluginNotFound)

**Comment by kou** [comment]
You need to follow the instruction described in README.md:

```console
$ cd redmine/plugins
$ git clone https://github.com/clear-code/redmine_common_mark.git common_mark
$ cd ..
$ bundle install
```
